AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - config/application.rb
    - config/initializers/sorcery.rb
    - db/seeds/**/*
    - db/schema.rb
    - public/uploads/**/*
    - tmp/**/*
Rails:
  Enabled: true
Metrics/LineLength:
  Enabled: false
require: rubocop-rspec
Style/Documentation:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
